### ISSUE TITLE
Secrets vs Figaro

### ISSUE THREAD

**Issue by jandudulski** [monterail/guidelines#206]
Which one should we use since rails 4.1? I started using in my private project [secrets](http://guides.rubyonrails.org/4_1_release_notes.html#config-secrets-yml) and it just works.

pros for secrets:
* built-in
* default way to provide `secret_key_base`
* default way to provide credentials for production `database.yml`

cons:
* access only via `Rails.application.secrets` vs shorter `Figaro.env` and `ENV` in Figaro

Any thoughts?

**Comment by teamon** [comment]
I guess we've agreed on using [ENVied](https://github.com/eval/envied). @jandudulski can you make a PR?

**Comment by jandudulski** [comment]
Sure!
