### ISSUE TITLE
Ruby version in Gemfile

### ISSUE THREAD

**Issue by kapone89** [monterail/guidelines#226]
Adam Hodowany asked me to add issue about storing ruby version in Gemfile. He think that we should discuss it.

**Comment by chytreg** [comment]
In case where you use heroku-build-pack ruby version in Gemfile is required.
You can always use ENV to temporally use another ruby.

```ruby
source 'https://rubygems.org'
gem 'bundler', '>= 1.7.0'

ruby ENV['GEMFILE_RUBY'] || '2.2.2'
```

```bash
export GEMFILE_RUBY=2.1.2; rails s
```

**Comment by jandudulski** [comment]
:+1: for @chytreg

**Comment by teamon** [comment]
:+1: @kapone89 (or @hodak) please make a PR.

**Comment by hodak** [comment]
https://github.com/monterail/guidelines/pull/239 merged
