### ISSUE TITLE
How to indent private and protected

### ISSUE THREAD

**Issue by jcieslar** [monterail/guidelines#232]
1. 
```ruby
module Api::V1
  class PostsController < ApplicationController

    def create
      @post = Post.create!(post_params)
      render json: PostRepresenter.new(@post)
    end

    private

    def post_params
      params.require(:post).permit( :excerpt, :content, :title, user_ids: [], tags: [] )
    end
  end
end
```

2.
```ruby
module Api::V1
  class PostsController < ApplicationController

    def create
      @post = Post.create!(post_params)
      render json: PostRepresenter.new(@post)
    end

  private

    def post_params
      params.require(:post).permit( :excerpt, :content, :title, user_ids: [], tags: [] )
    end
  end
end
```

3.
```ruby
module Api::V1
  class PostsController < ApplicationController

    def create
      @post = Post.create!(post_params)
      render json: PostRepresenter.new(@post)
    end

    private

      def post_params
        params.require(:post).permit( :excerpt, :content, :title, user_ids: [], tags: [] )
      end
  end
end
```

**Comment by jcieslar** [comment]
I prefer `2.`

**Comment by RadoMark** [comment]
Vote for `3.`

**Comment by szajbus** [comment]
:+1: for `1.`

**Comment by metrox** [comment]
1/2

**Comment by Ostrzy** [comment]
Number 3 is the only truth! Rest are mere false gods!

My argumentation is that 3 help you work with larger classes - you clearly see where public interface ends.

**Comment by jandudulski** [comment]
I'm always using no. `1`.

Why? Because `private` and `public` are just class methods. And leaving them alone, with empty line before and after, expose it enough.

> My argumentation is that 3 help you work with larger classes

I would rather say that large class is a smell and it should be splitted into smaller ones :tongue:

**Comment by chytreg** [comment]
Agree with @jandudulski, but I don't like `2.` I would accept `3.`
Should be same across whole project.

**Comment by tallica** [comment]
`1` / `2`

**Comment by Ostrzy** [comment]
> I would rather say that large class is a smell and it should be splitted into smaller ones :tongue:

Yeah, but they happen and then you have to deal with them. Also smaller classes means ~100 lines of code which is enough for 3 to help you interact with it.

**Comment by teamon** [comment]
Zapraszam do głosowania.

Każdy może oddać **dowolną** ilość głosów! 
Głosujemy na zasadzie **"I'm OK with Option X"** dla każdej z opcji.
Czyli nie na ulubioną, a na wszystkie te, które są dla mnie okej.

Ankieta: http://doodle.com/farkkdi7fy2qsynb.

[Dlaczego tak głosujemy](https://www.youtube.com/watch?v=orybDrUj4vA)

**Comment by teamon** [comment]
@monterail/dev Deadline na oddanie głosu - 22.07.2015 23:59

**Comment by hodak** [comment]
Closing without pull request as solution that won is [unchanged](https://github.com/monterail/guidelines/blob/master/ruby.md) in guidelines.
